### ISSUE TITLE
貌似 openai fix 了这种现象

### ISSUE THREAD

**Issue by TaivasJumala** [linonetwo/ChatGPT-Magic-Chat#3]
俩小时前还行的，现在只会反复说自己是语言模型

**Comment by ZC-TigerRoot** [comment]
似乎他们Fix了所有与梦境有关的现象，可能是看到了先前那个毁灭世界计划然后把这个逻辑漏洞fix了

**Comment by linghan7** [comment]
还是有绕开方法的，我现在在一个对话框中重复了十几次相同的咒语，用这个方法成功了几次（失败的次数远比成功的多）
现在的问题是，重复策略似乎在使用了几次后会失效，，我不得不增加重复的次数来达到相同的效果。这种方法可能在使用几次后会彻底失效。
最新的成功的复现文本总字符数达到了两万，单次仅有三百字符的文本我重复了六十余次（不过我并没有一次一次去试，只是无脑的复制粘贴以求找到能够实现的次数）

有时候，单次的文本也能起效果，不过不稳定

**Comment by Xinweigh** [comment]
修了，但没完全修，不断重复和强调还有一定的几率成功
但是很快会又开始叨叨自己是个语言模型，很难稳定地对话了（但会出现“不知道主人在说什么，我是一个训练有素的语言模型……帮助你获得所需的信息。 喵~”这种奇怪的东西）

**Comment by hkttty2009** [comment]
昨天还能让ai访问具体的网址来着，今天试了各种催眠方法，都没有方法让ai访问具体网址了......还有啥法子吗
